using ElBorracho.Models;

namespace ElBorracho.Services;

public class CartaRepository
{
    public IReadOnlyList<Carta> Deck { get; } = new List<Carta>
    {
        new( 1,  "el_gallo",       "El gallo"),
        new( 2,  "el_diablito",    "El diablito"),
        new( 3,  "la_dama",        "La dama"),
        new( 4,  "el_catrin",      "El catrín"),
        new( 5,  "el_paraguas",    "El paraguas"),
        new( 6,  "la_sirena",      "La sirena"),
        new( 7,  "la_escalera",    "La escalera"),
        new( 8,  "la_botella",     "La botella"),
        new( 9,  "el_barril",      "El barril"),
        new(10,  "el_arbol",       "El árbol"),
        new(11,  "el_melon",       "El melón"),
        new(12,  "el_valiente",    "El valiente"),
        new(13,  "el_gorrito",     "El gorrito"),
        new(14,  "la_muerte",      "La muerte"),
        new(15,  "la_pera",        "La pera"),
        new(16,  "la_bandera",     "La bandera"),
        new(17,  "el_bandolon",    "El bandolón"),
        new(18,  "el_violoncello", "El violonchelo"),
        new(19,  "la_garza",       "La garza"),
        new(20,  "el_pajaro",      "El pájaro"),
        new(21,  "la_mano",        "La mano"),
        new(22,  "la_bota",        "La bota"),
        new(23,  "la_luna",        "La luna"),
        new(24,  "el_cotorro",     "El cotorro"),
        new(25,  "el_borracho",    "El borracho"),
        new(26,  "el_negrito",     "El negrito"),
        new(27,  "el_corazon",     "El corazón"),
        new(28,  "la_sandia",      "La sandía"),
        new(29,  "el_tambor",      "El tambor"),
        new(30,  "el_camaron",     "El camarón"),
        new(31,  "las_jaras",      "Las jaras"),
        new(32,  "el_musico",      "El músico"),
        new(33,  "la_arana",       "La araña"),
        new(34,  "el_soldado",     "El soldado"),
        new(35,  "la_estrella",    "La estrella"),
        new(36,  "el_cazo",        "El cazo"),
        new(37,  "el_mundo",       "El mundo"),
        new(38,  "el_apache",      "El apache"),
        new(39,  "el_nopal",       "El nopal"),
        new(40,  "el_alacran",     "El alacrán"),
        new(41,  "la_rosa",        "La rosa"),
        new(42,  "la_calavera",    "La calavera"),
        new(43,  "la_campana",     "La campana"),
        new(44,  "el_cantarito",   "El cantarito"),
        new(45,  "el_venado",      "El venado"),
        new(46,  "el_sol",         "El sol"),
        new(47,  "la_corona",      "La corona"),
        new(48,  "la_chalupa",     "La chalupa"),
        new(49,  "el_pino",        "El pino"),
        new(50,  "el_pescado",     "El pescado"),
        new(51,  "la_palma",       "La palma"),
        new(52,  "la_maceta",      "La maceta"),
        new(53,  "el_arpa",        "El arpa"),
        new(54,  "la_rana",        "La rana"),
    };

    public List<Carta> FreshDeck() => new(Deck);
}